New FenderStrings
FenderLang/Fender pull request #108
Opened 2023-05-01 16:54 UTC by FuzzyNovaGoblin

this change is not done yet it still needs to have some methods implemented for strings that were previously only implemented for lists, and there are a number of times where `toString` is called to use the rust std string functions but these methods can be implemented for the `FenderString` to eliminate those `toString` calls

2023-06-19 17:43 UTC, Redempt commented on src/type_sys/fender_value/fender_strings.rs
> +    cacheable: bool,
So is the point that you can create some strings that will never be cached? I'm not really sure why we need this field.

2023-06-19 17:45 UTC, Redempt requested changes
Since this is such a large changeset, could you try to summarize some of what you did? Some things in here seem unrelated to fender strings.

2023-06-19 17:45 UTC, Redempt commented on src/type_sys/fender_value/fender_strings.rs
> +    pub fn insert_char(&mut self, index: usize, value: char) -> bool {
With us introducing all of these functions, I would like to have at least a few unit tests for them. Could we create something like `ensure_valid` that makes sure the char vec and the cached string are identical, and then use that for assertions in tests?

2023-06-19 17:48 UTC, Redempt commented on src/type_sys/fender_value/mod.rs
> +            FenderValue::String(s) => s.iter().collect(),
Is there a way to get the cached string? For example, I think `print_func` still uses `to_string` and so would copy the whole string whenever it's printed. Maybe we need to have a way to convert a type into an `impl IntoIterator<Item = char>`?

2023-06-26 15:42 UTC, FuzzyNovaGoblin commented
its not letting me comment on it but @Redempt said
> Since this is such a large changeset, could you try to summarize some of what you did? Some things in here seem unrelated to fender strings.

Can you give an example? I went through quickly and didn't see anything that wasn't just updating stuff to work with the new strings or the creation of the new strings themselves. I did see a macro for writing the out of bounds errors because there was just a lot of duplication and wanted to make sure they were all the same, but even that was because I was adjusting methods for the new strings.

2023-06-26 15:46 UTC, Redempt commented
Okay, I left that comment a while ago so I don't know what I was talking about specifically anymore.

2024-03-14 14:55 UTC, closed without merging